title: MECS program
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Robomech Work Group: https://github.com/just-the-docs/just-the-docs-template

defaults:
  - scope:
      path:
      type: "pages"
    values:
      layout: "default"

plugins:
  - Jekyll-last-modified-at

back_to_top: true
back_to_top_text: "Back to top"
footer_enable: true

last_edited:
  enabled: true
  date_format: "%Y-%m-%d"
  time_format: "%H:%M:%S"
