title: Robo-MECS
description: A technical documentation for Robomech Factory forcused on Mechanism, Electronics, Control, Software.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Robomech Work Group: https://github.com/Robomech-UEC

logo: "/assets/images/RMF_logo.png"

plugins:
  - jekyll-last-modified-at

# attach default to all the pages
defaults:
  - scope:
      path:
      type: "pages"
    values:
      layout: "default"

back_to_top: true
back_to_top_text: "先頭に戻る"

footer_enable: true

last_modified_at:
  enabled: true
  date_format: "%Y-%m-%d"

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: "k"